### PR TITLE
Get and display world record from speedrun.com

### PR DESCRIPTION
**Pull request by 4ilo**
- New global setting to toggle display of world record
schermafbeelding 2018-02-18 om 14 44 09

- Display record in the run footer
schermafbeelding 2018-02-18 om 14 39 07

- Add the world record info from speedrun.com per run/save file
schermafbeelding 2018-02-18 om 14 38 23

- Dialog for easy searching and selection from the speedrun.com api
schermafbeelding 2018-02-18 om 14 38 55

### CODE REVIEW

**Comment by gered** [comment]
This looks great! :+1: Thanks for the contribution.

I'll review it a bit more either later today or tomorrow before merging it, and will package it up as a new release (v1.5.5) if I don't run into any issues.

**Comment by 4ilo** [comment]
If you encounter any issues or problems, feel free to give me some feedback and i will try to fix them.

**Comment by gered** [comment]
Four months late! :'( I'm very sorry! Thanks for your efforts with this, it looks great to me. I'll package up a new release with this right now.

**Comment by gered** [comment]
Hrmm, actually I'll hold off on packaging a new release for now. I just ran into some issues with the search appearing to freeze (searching for "zelda" but any other search results in the same behaviour... which is strange as it worked fine for me 20 minutes ago... maybe network related, will investigate more shortly).

**EDIT**: Nevermind, an error dialog was popping up saying "Could not connect to speedrun.com" (via `showError()`), but for some reason it was popping up _behind_ the "World Record selection" dialog, so I never saw it and just assumed the app had frozen while waiting for a network response or similar. Anyway, I'll see about tweaking the error dialog so it doesn't show up behind like this.

**Pull request merged**
